name: Python Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  pythonCommandDispatch:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'obwando/pyflow'
        token: ${{ secrets.PAT }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt
        
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Run script
      run: python main.py
      env:
        github_context: ${{ toJSON(github) }}
        eventdata: ${{ toJSON(github.event) }}
        token: ${{ secrets.PAT }}
